# Generated by Django 2.0.6 on 2018-07-11 06:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('qna', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='acceptedanswer',
            field=models.IntegerField(default=None, null=True),
        ),
    ]
